version: '3.2'

services:
  #############################################
  # Start http://api:3000/
  #############################################
  api:
    # if not --build and kursplan-api already exists in
    # your local computers registry 'image' is used.
    image: $LOCAL_IMAGE_ID

    environment:
      SERVICE_PUBLISH: '/api/kursplan'
      SERVER_PORT: 3000
      API_KEYS_2: '?name=kursplan&apiKey=&scope=read'
      API_KEYS_1: '?name=kursinfo&apiKey=&scope=read'
      API_KEYS_0: '?name=kursinfo-web&apiKey=&scope=read'
      KURSPLAN_API_KEYS: '?name=kursplan&apiKey=&scope=read'
      REDIS_URI: 'redis://localhost:6379/'
      LOGGING_ACCESS_LOG: 'true'

    ports:
      - 3000

  #############################################
  # Start the client running tests
  # agains http://api:3000/
  #############################################
  integration-tests:
    # Build client image and run tests
    # from inside that.
    build: ./test/integration
    depends_on:
      - api
