version: '3.7'

services:
  api:
    image: $LOCAL_IMAGE_ID

    environment:
      SERVICE_PUBLISH: '/api/kursplan'
      SERVER_PORT: 3000
      API_KEYS_2: '?name=test&apiKey=1234&scope=read'
      API_KEYS_1: '?name=test&apiKey=1234&scope=read'
      API_KEYS_0: '?name=test&apiKey=1234&scope=read'
      KURSPLAN_API_KEYS: '?name=test&apiKey=1234&scope=read'
      REDIS_URI: 'redis://localhost:6379/'

  integration:
    build: ./test/integration
    environment:
      INTEGRATION_TEST_BASEURL: 'http://api:3000/api/kursplan'
      INTEGRATION_TEST_SUCCESS_DELAY: '${SUCCESS_DELAY:-0}'
      INTEGRATION_TEST_FAILURE_DELAY: '${FAILURE_DELAY:-0}'
      WAIT_HOSTS: 'api:3000'
      WAIT_HOSTS_TIMEOUT: 30
    depends_on:
      - api
